### ISSUE TITLE
zip file is not created in php 8.0 

### ISSUE THREAD

**Issue by sandeepavasthi01** [chamilo/pclzip#3]
Errors are coming on PHP 8.0 

<b>Fatal error</b>:  Uncaught ValueError: Path cannot be empty in /var/www/html/socialapp/ls-local/pclzip.lib.php:2353
Stack trace:
#0 /var/www/html/socialapp/ls-local/pclzip.lib.php(2353): fopen()
#1 /var/www/html/socialapp/ls-local/pclzip.lib.php(2133): PclZip-&gt;privOpenFd()
#2 /var/www/html/socialapp/ls-local/pclzip.lib.php(2169): PclZip-&gt;privCreate()
#3 /var/www/html/socialapp/ls-local/pclzip.lib.php(592): PclZip-&gt;privAdd()
#4 /var/www/html/socialapp/ls-local/index.php(404): PclZip-&gt;add()
#5 {main}
  thrown in <b>/var/www/html/socialapp/ls-local/pclzip.lib.php</b> on line <b>2353</b><br />

**PHP Platform : 8.0**

**Comment by jawharjob** [comment]
I have the same problem

**Comment by sandeepavasthi01** [comment]
> I have the same problem

You have used $zip = new ZipArchive; this function in php 8.0

**Comment by williamdes** [comment]
Read the code and you will notice that `new PclZip()` needs a first argument to set the `zipname` and fopen should be happy
let me know

**Comment by tofurky** [comment]
A bit late to the party here, but this is actually due to a change in PHP 8 regarding how constructors are defined.

Rather than a function with the name of the class as is done in pclzip.lib.php:
`function PclZip($p_zipname)`

It needs to be renamed like this:
`function __construct($p_zipname)`

Otherwise, the filename passed when constructing the PclZip object is discarded, leading to the error seen.
